# Generated by Django 5.0.6 on 2024-07-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tekkicrudapp', '0003_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_retrieved',
            field=models.IntegerField(default=0),
        ),
    ]
