# Generated by Django 5.0.6 on 2024-07-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tekkicrudapp', '0005_remove_product_max_retrieved'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='retrieval_count',
            field=models.IntegerField(default=0),
        ),
    ]
