# Generated by Django 5.0.6 on 2024-07-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tekkicrudapp', '0006_product_retrieval_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='retrieval_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
